export { googleMapsService } from './googleMaps.service'
export { restaurantService } from './restaurant.service'
export { recommendationService } from './recommendation.service'
export { userService } from './user.service'
export { authenticationService } from './authentication.service'
export { categoryService } from './category.service'
export { historyService } from './history.service'
export { pictureService } from './picture.service'